### ISSUE TITLE
No meridian labels in display

### ISSUE THREAD

**Issue by pkmn99** [matplotlib/basemap#280]
Here is my simple code to darw a map over China.
But it is strange to me that there is no meridian labels in the figure even though I set it.

`from mpl_toolkits.basemap import Basemap
import numpy as np
import matplotlib.pyplot as plt

# Plot map
plt.figure(figsize=(7,6))
m = Basemap(projection='cyl',\
            llcrnrlon=70,llcrnrlat=10,\
            urcrnrlon=140,urcrnrlat=55,\
            resolution='l', area_thresh=10000)
m.drawparallels(np.arange(10,55,10),labels=[1,0,0,0],fontsize=10)
m.drawmeridians(np.arange(70,140,10),lables=[0,0,0,1],fontsize=10)
m.drawcoastlines()
m.drawcountries()
plt.show()
`
I don't know what goes wrong with my code.

![figure_1](https://cloud.githubusercontent.com/assets/17201113/13826313/28a3cd9c-eb8d-11e5-81ae-ac67890ab3c3.png)

**Comment by WeatherGod** [comment]
You have a typo in one of the keyword arguements: "lables" --> "labels".

Unfortunately, because of the function API, any unused keyword arguments gets passed on to other functions. Those, in turn, pass on unused keyword arguments to other functions as well. It is turtles all the way down!

At the bottom of the stack in matplotlib, some places do checking for unused arguments, and some do not. This is largely because of an old design decision that there would be a "giant pool of keywords" and each function should just take what is relevant to them and either ignore the rest or pass them along. Because of this, there is very little error checking to find typos like this. There is work going on in matplotlib to improve this situation, though.

I'll close this issue as it isn't a bug.

**Comment by pkmn99** [comment]
Thank you for pointing out this typo. Sorry for my careless mistake...
I tried everything but I just missed this small typo.
Previously I thought a typo like this would raise an error. For example if the keyword "linewidth" is misspelled as "linewideth" for drawmeridians, an error will occur. But this is not for keyword "labels". 
Your explanation is indeed helpful. 
Thanks!
