### ISSUE TITLE
Basemap License

### ISSUE THREAD

**Issue by ocefpaf** [matplotlib/basemap#282]
What is basemap's license? `setup.py` says [`OSI Approved`](https://github.com/matplotlib/basemap/blob/master/setup.py#L134) and [PKG-INFO](https://github.com/matplotlib/basemap/blob/f70b00cb967a5565da92cce4e36253d73ffca98c/PKG-INFO#L8) says `UNKNOWN`.

**Comment by WeatherGod** [comment]
Good question. Looks like the license is in the README.md, but it doesn't look like a typical 2/3-clause BSD...
```
copyright (c) 2011 by Jeffrey Whitaker.

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notices appear in all copies and that
both the copyright notices and this permission notice appear in
supporting documentation.
THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, INDIRECT OR
CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
```
What is that? Is that MIT?

**Comment by ocefpaf** [comment]
Looks like the old-style MIT.  Thanks!

https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT

**Comment by QuLogic** [comment]
Specifically, https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Old_Style_with_legal_disclaimer_3

However, I think this should be made a bit more clear everywhere.

**Comment by molinav** [comment]
@ocefpaf The original license used to be the Historical Permission Notice and Disclaimer ([HPND](https://opensource.org/licenses/HPND)) but in fact `basemap` was GPLv2+ as a whole because of the data files included from GMT 4.x.

I contacted recently @jswhit and he agreed with replacing the HPND into the more standard MIT license (whose text is almost identical). Also, the data files were updated in 2016 with the new GSHHG 2.3.6 plus GMT 5.x, whose license is now LGPLv3+, so actually the license in `basemap` was still enforcing GPLv2+ without being needed anymore.

I made a bit of rearranging in all these license files to make it clearer. For the next stable release (1.3.0, to be ready soon), the summary would be:
* `basemap`: MIT (with bundled `libgeos_c.so` under LGPLv2.1-only).
* `basemap-data`: LGPLv3+ (some files also under MIT).
* `basemap-data-hires`: LGPLv3+.

This also means that `basemap` will not cause a cascading of the GPLv2+ into derivative works from `basemap`1.3.0 onwards.

**Comment by WeatherGod** [comment]
A bit of additional history... I have had discussions with those who
maintain GMT a few years ago about their license. The discussion centered
around whether or not it was even valid to apply a software license to data
files. Basically, my interpretation of the situation was that the GMT data
files were potentially unlicensed and that they needed an open data license
such as a creative commons license in order for them to really be properly
protected.

Legal questions aside, as a practical matter, the authors of GMT were well
aware of Basemap's usage of their GSHHS data and they seemed perfectly fine
with how basemap was being used and distributed. It also should be noted
that the actual GSHHS data itself was never actually bundled with basemap.
Rather, GMT was used to do an initial preprocessing of the original data,
and then some python scripts in the codebase would extract out the needed
information and store it into an easy-for-basemap-to-use form. So, because
of these hoops the data had to jump through, I had serious doubts that a
software license was even applicable.
