### ISSUE TITLE
Site https://matplotlib.org/basemap/ is displaying Insecure Connection?

### ISSUE THREAD

**Issue by crazyBaboon** [matplotlib/basemap#346]
I am using firefox on Win 10. When I try to access the website, the browser displays 

"Your connection is not secure

The owner of matplotlib.org has configured their web site improperly. To protect your information from being stolen, Firefox has not connected to this web site."

Why is this happening?

**Comment by jenshnielsen** [comment]
See https://github.com/matplotlib/matplotlib/issues/8302 for more information this basically happens because we are hosting our documentation on github pages so the certificate is for github.io rather than matplotlib.org 

For now i suggest using http://matplotlib.org/basemap/  instead of https://matplotlib.org/basemap/

**Comment by crazyBaboon** [comment]
Thanks!
