### ISSUE TITLE
Incompatibility with python 3: dividing integer indices by 2 in various places must be replaced with floor divide //.

### ISSUE THREAD

**Issue by lukelbd** [matplotlib/basemap#351]
I'm very surprised I'm the first to notice this; there are several places in `basemap/__init__.py` where integer indices are divided by 2 (`/`) instead of floor-divided by 2 (`//`), which causes errors when python tries to do float-indexing. This should be changed. To maintain compatibility with python 2, if I recall correctly, one can use `from __future__ import division`.

**Comment by WeatherGod** [comment]
Pretty sure we already fixed this a while back. Can you point out where in master you are seeing this?

**Comment by lukelbd** [comment]
Looks like Anaconda still only has version `1.0.7` available. I tried directly installing version `1.1.0` but it failed. I guess that is a different issue. Will download and compile directly, but I suppose that should also be addressed; thanks.

**Comment by lukelbd** [comment]
Yep, that's the problem: your [last formal release was version 1.0.7 in 2013](https://github.com/matplotlib/basemap/releases).

**Comment by ocefpaf** [comment]
@lukelbd note that the channel `defaults` only ships version 1.0.7 because that is the last released version.
See https://pypi.python.org/pypi/basemap/1.0.7 and https://github.com/matplotlib/basemap/releases

The `conda-forge` channel does have an updated "dev" version of `basemap` though. Try,

```shell
conda install basemap basemap-data-hires -c conda-forge
```

note that in `conda-forge` the high resolution data is in another package to ship a lighter `basemap` for those who don't need high resolution.

**Comment by lukelbd** [comment]
Great, thanks! Yup, I noticed that and edited my comment. Although it looks like `conda-forge` has only version `1.0.8` (which does use floor division for indexing). Is the latest version `1.1.0` still in testing?

**Comment by ocefpaf** [comment]
Updating it now... Hold on!

**Comment by WeatherGod** [comment]
Yeah, sorry, I have been so distracted with work that I haven't actually
tagged and released v1.1.0 (but it is what it is in master). v1.0.8 was an
"unofficial" release, but also never tagged.

I am doing what I can to slowly kill basemap and move the world over to
cartopy...

**Comment by lukelbd** [comment]
Very cool, thanks. Yes `cartopy` is clearly the future to me, I investigated that. Much more objected oriented and no more worrying about dateline wrapping of lines/polygons/contours. Unfortunately for the time being basemap is **way** more feature rich; for example, labelling longitudes/latitudes is unavailable for most projections and severely limited for the only 2 where it is available (Mercator and Plate-Carree), which was a deal-breaker for me. Maybe in a year or two.

**Comment by WeatherGod** [comment]
Closing now because I assume the problem is indeed already fixed.

In my release notes for v1.1.0, I state that I will be supporting basemap until the EOL of python2.7 -- not that that means much, as I am only maintaining it for legacy applications at work. I'll review new PRs, and I'll make sure it works with newer versions of numpy, matplotlib and proj.4, but only until py27 is EOL'ed.

Any feature in basemap that isn't in cartopy should be considered a bug in cartopy at this point. So, any contribution efforts you wish to make should be to cartopy, not basemap.

Cheers!

**Comment by lukelbd** [comment]
@WeatherGod Thanks again, and good to know. I'll take a crack at it in the following weeks if I have free time, I've never contributed before but I suppose that's how these things move forward. I may start another issue thread related to longitude/latitude line labelling on the `cartopy` page.
