### ISSUE TITLE
geos projection cannot cross pole

### ISSUE THREAD

**Issue by sfinkens** [matplotlib/basemap#361]
Defining a Basemap in geostationary projection,

    >>> from mpl_toolkits.basemap import Basemap
    >>> Basemap(projection='geos', lon_0=0)

fails in basemap-1.1.0 with the following error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "...lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 1109, in __init__
	self._readboundarydata('gshhs',as_polygons=True)
      File "...lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 1241, in _readboundarydata
	raise ValueError('%s projection cannot cross pole'%(self.projection))
    ValueError: geos projection cannot cross pole

**Comment by WeatherGod** [comment]
How did you install Basemap and it's accompanying data? The data was
updated in 1.1.0 as well as a few tweaks to the loading code. I never
tested the loading code against the old data, so there might be some
incompatibilities.

On Jul 4, 2017 12:36 PM, "Stephan Finkensieper" <notifications@github.com>
wrote:

Defining a Basemap in geostationary projection,

>>> from mpl_toolkits.basemap import Basemap
>>> Basemap(projection='geos', lon_0=0)

fails in basemap-1.1.0 with the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py",
line 1109, in __init__
self._readboundarydata('gshhs',as_polygons=True)
  File "...lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py",
line 1241, in _readboundarydata
raise ValueError('%s projection cannot cross pole'%(self.projection))
ValueError: geos projection cannot cross pole

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/matplotlib/basemap/issues/361>, or mute the thread

**Comment by Funkensieper** [comment]
I used

    pip install --prefix=$PREFIX git+https://github.com/matplotlib/basemap.git

**Comment by WeatherGod** [comment]
Do you have the same problem if installing from conda-forge?

**Comment by Funkensieper** [comment]
Unfortunately I can't use conda due to legal issues...

**Comment by WeatherGod** [comment]
uhm, ok. I take it that there is a long an complicated story behind that.
I'll see if I can reproduce the problem, but right now, conda is the
preferred method of installing packages that have non-python dependencies
(namely, libgeos).

**Comment by Funkensieper** [comment]
Indeed :) Thank you very much for your effort! I linked basemap against geos-3.6.1, whose test suite passes.

**Comment by WeatherGod** [comment]
basemap's test suite? yeah, that isn't very definitive because it isn't
extensive at all. The better exercise is to run the examples (needs netcdf4
package, though).

**Comment by Funkensieper** [comment]
Aha, the geos definition in ``examples/test.py``, 

    m = Basemap(projection='geos',
                rsphere=(6378137.00,6356752.3142),
                resolution='c',
                area_thresh=10000.,
                lon_0=0,
                satellite_height=35785831)
works fine. Removing the ``rsphere`` argument causes the error again.

**Comment by WeatherGod** [comment]
Interesting. I guess that makes some sense, but perhaps a better default
behavior could be defined?

**Comment by Funkensieper** [comment]
Hmm, I don't see why a geostationary projection would not be defined for a spherical earth?

**Comment by WeatherGod** [comment]
it might be expecting a tuple and erroring on a float or something

I'll look into it tomorrow

**Comment by sebhahn** [comment]
just stumbled on this issue myself, any progress?

**Comment by Rigonz** [comment]
Same for me:  removing the parameter rsphere=(6378137.00,6356752.3142) triggers the error, but including it brings no result.

**Comment by ebo** [comment]
I can confirm that this is still the case for Baseline-1.2.0 and geos-3.6.2.  Adding rsphere=(6378137.00,6356752.3142) fixes the problem.

**Comment by Rehan418** [comment]
> Aha, the geos definition in `examples/test.py`,
> 
> ```
> m = Basemap(projection='geos',
>             rsphere=(6378137.00,6356752.3142),
>             resolution='c',
>             area_thresh=10000.,
>             lon_0=0,
>             satellite_height=35785831)
> ```
> 
> works fine. Removing the `rsphere` argument causes the error again.

It worked for me.thank you.

**Comment by AlisonVilela** [comment]
> Aha, the geos definition in `examples/test.py`,
> 
> ```
> m = Basemap(projection='geos',
>             rsphere=(6378137.00,6356752.3142),
>             resolution='c',
>             area_thresh=10000.,
>             lon_0=0,
>             satellite_height=35785831)
> ```
> 
> works fine. Removing the `rsphere` argument causes the error again.

It worked for me too. Thank you!
