### ISSUE TITLE
using basemap on azure notebooks

### ISSUE THREAD

**Issue by leomiquelutti** [matplotlib/basemap#422]
Dear,

I am trying to execute some codes on the (also) free cloud service provider [Microsoft Azure Notebooks](https://notebooks.azure.com) for jupyter notebooks that depend on __Basemap__ but have not been able to.

A way to fetch codes on Azure Notebooks is through `!pip install package`, but I didn't succeed with Basemap. Is there a way to run Basemap there?

**Comment by WeatherGod** [comment]
The recommended way to install basemap, is through conda-forge, so run
`!conda install -c conda-forge basemap` (assuming that conda is already
installed).

**Comment by phobson** [comment]
Just a quick note, if you're trying to install from the notebook itself, you'll need to change the command from @WeatherGod to:

`conda install -c conda-forge basemap --yes`

Since you won't be able to answer the Yes/No prompt interactively

**Comment by leomiquelutti** [comment]
Sorry for the late reply. Thank you guys for the comments.

The `!conda install -c conda-forge basemap`  totally crashed my Azure Notebook environment. 

I can't even say that the `!conda install -c conda-forge basemap --yes` will work because I still couldn't fix the environment to try it.  Once I fix it, I'll get back here to give you feedback.

**Comment by rezapci** [comment]
Did you fix it ?

**Comment by rezapci** [comment]
this is the fix for notebook.azure `!pip install https://github.com/matplotlib/basemap/archive/master.zip`

**Comment by leomiquelutti** [comment]
Nope! My azure notebook environment is still crashed - take a look at [this](https://github.com/Microsoft/AzureNotebooks/issues/448#issuecomment-422833013) issue. I didn't have the patience to start everything over.

I overcame the problem using [mybinder](https://mybinder.org/)

**Comment by molinav** [comment]
We now have precompiled binary wheels for Windows, so it should be possible to install `basemap` with `pip` as you would do with any other package (for Windows x86 and x64, Python 2.7 and 3.5-3.9):
```sh
!pip install basemap
```
In case you need the high-resolution datasets, you need to install them manually:
```sh
!pip install basemap-data-hires
```
The solution by @rezapci will not work at the moment, because the refactoring of `basemap` into three separate packages (`basemap`, `basemap-data` and `basemap-data-hires`) implied the movement of the `setup.py` file to another place different from the project top-level folder, so `pip` will not know what to do with the repository zip.

If this solution still does not solve your problem, feel free to reopen this issue or create a new one.
