### ISSUE TITLE
sample data file not found

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [matplotlib/basemap#438]
I'm looking at https://matplotlib.org/basemap/users/examples.html, specifically, at the example entitled "Pseudo-color plot of SST and sea ice analysis".  When I try to run that example, I get an I/O error at the statement that attempts to load the dataset:

dataset= Dataset('http://www.ncdc.noaa.gov/thredds/dodsC/OISST-V2-AVHRR_agg')

It appears that this file no longer exists.

**Comment by Awaiskhan404** [comment]
Dataset might need some authorization. Still, facing issues?

**Comment by molinav** [comment]
It seems the link from the example is not available anymore. This is something outside of our control. We should update the documentation though.

I guess the original authors rearranged the website, see e.g.
https://psl.noaa.gov/data/gridded/data.noaa.oisst.v2.highres.html

In particular, you can find two OISST product files for the periods 1971-2000 and 1991-2020 here:
https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.ltm.1971-2000.nc
https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.ltm.1991-2020.nc

I know the documentation *does need* an update, but before updating the documentation I am still fixing obvious bugs around. Any help is welcome. ;-)

**Comment by molinav** [comment]
In release 1.4.0, I have updated this example in the `basemap` documentation so that it uses files from the following URL:
https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2.highres

The documentation examples for `basemap` 1.4.0 can be found now under the following link:
https://matplotlib.org/basemap/1.4.0/users/examples.html

I discarded using the equivalent thredds dods service, because the access was usually hanging or causing timeout. The example now takes longer to execute, because it downloads the complete datasets, but it turned to be more stable in this way.
