### ISSUE TITLE
installing Basemap on Centos without root privileges

### ISSUE THREAD

**Issue by bruhwiler** [matplotlib/basemap#471]
I ran into a few technical issues, when trying to install Basemap on a Centos Linux box where I did not have root privileges.

This is a very specific case, so I don't know how helpful it will be, but in any case, I documented the instructions in a public 'gist' here:
https://gist.github.com/bruhwiler/5108aecce94da0532c9f275f3b0b4d9d

The step-by-step instructions are a bit overly detailed, because I did this for a student who was not familiar with Linux, nor with the JupyterLab UI.

**Comment by molinav** [comment]
Thanks for your contribution, @bruhwiler! I know it has been a long time since the issue was open, but I wanted to share with you that the complexity of the installation process has been reduced significantly in the last couple of years. Manylinux wheels are available on PyPI:
```
python -m pip install basemap
```
as well as `conda-forge` packages:
```
conda install -c conda-forge basemap
```
This means that the installation can be performed with precompiled binary packages, without the need of building everything from source. The installation procedure is now described in the documentation too:
https://matplotlib.org/basemap/1.4.0/users/installation.html
