### ISSUE TITLE
How to get the coordinate of a boundary line.

### ISSUE THREAD

**Issue by jxalfoudqt** [matplotlib/basemap#472]
Dear all,

I can draw the map of Australia continent, but I want to get the coordinate (lon_X, Lat_Y) of the Australia continental boundary line. Does anyone know how to realize it?

Many thanks.
Tao

**Comment by WeatherGod** [comment]
This isn't really possible to do with basemap. Particularly the problem is
that the path data for the various boundaries are not indexable by any
categories. All of the lines and polygons that basemap provides are just
flat lists of those features, with no way to map back to information like
the country name, continent, etc.

Now, it might be possible to do it with the GSHHS dataset, which basemap
uses as a basis for its maps: https://www.soest.hawaii.edu/pwessel/gshhg/
