### ISSUE TITLE
ImportError: cannot import name 'dedent' from 'matplotlib.cbook' 

### ISSUE THREAD

**Issue by adibratul** [matplotlib/basemap#494]
while installing basemap in ubuntu  using following code 

`from mpl_toolkits.basemap import Basemap`

got the following file missing. 

```
`Traceback (most recent call last):

  File "<ipython-input-9-d9467465a3b6>", line 1, in <module>
    from mpl_toolkits.basemap import Basemap

  File "/home/adib/.local/lib/python3.7/site-packages/mpl_toolkits/basemap/__init__.py", line 50, in <module>
    from .proj import Proj

  File "/home/adib/.local/lib/python3.7/site-packages/mpl_toolkits/basemap/proj.py", line 6, in <module>
    from matplotlib.cbook import dedent

ImportError: cannot import name 'dedent' from 'matplotlib.cbook' (/home/adib/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py)`
```

**Comment by WeatherGod** [comment]
Whatever version of basemap you installed is not compatible with that
version of matplotlib. Use the most recent tarball from github.

Also, Basemap is no longer supported! The End of Life has been announced
years ago. Stop using basemap, use Cartopy instead!

**Comment by adibratul** [comment]
yes working with cartopy instead of basemap /. 
Thanks

**Comment by EJFielding** [comment]
@WeatherGod The present version of `proj.py` here on GitHub still has the import of `dedent` in line 6:
```
from matplotlib.cbook import dedent
```

**Comment by ReimarBauer** [comment]
this should become replaced by

from inspect import cleandoc as dedent

**Comment by SanjaySNegi** [comment]
I solved this problem downgrading matplotlib version to 3.2.
Follow the site link:---
https://stackoverflow.com/questions/63839163/maplotlib-and-basemap-cannot-import-name-dedent

**Comment by WeatherGod** [comment]
I just noticed that the basemap version is v1.3.0 from the main conda
channel. There is no such release:
https://github.com/matplotlib/basemap/tags. It would seem that conda
accidentally built a package using an older version of the code (because
this bug has been fixed for a while now). The correct solution would be to
install basemap version 1.2.2 from conda-forge and allow matplotlib to be
upgraded to whichever version you'd like.

Also, please move to cartopy!
