### ISSUE TITLE
Error to install with PIP

### ISSUE THREAD

**Issue by gavaza** [matplotlib/basemap#526]
```
# pip --version
pip 21.3.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

# pip install https://github.com/matplotlib/basemap/archive/master.zip#egg=basemap
Collecting basemap
  Downloading https://github.com/matplotlib/basemap/archive/master.zip (129.7 MB)
     |████████████████████████████████| 129.7 MB 10 kB/s              
ERROR: basemap from https://github.com/matplotlib/basemap/archive/master.zip#egg=basemap does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by molinav** [comment]
Which operating system are you using? If it is GNU/Linux (x86 o x64), you can use the precompiled binaries available in PyPI:
```sh
python -m pip install "basemap == 1.3.0b1" "basemap-data == 1.3.0b1"
```
It is the same problem as in #525, the direct pip installation from the GitHub repo is not working anymore because I have been restructuring the project folder structure in order to make the wheel packaging easier.

You would only need to install explicitly `basemap-data` until we have a stable release of 1.3.0 in PyPI, at that point `basemap` will install `basemap-data` automatically as dependency. If you need the high resolution datasets, you can install them from `basemap-data-hires`.
