### ISSUE TITLE
package import error

### ISSUE THREAD

**Issue by sahanaRavinder** [matplotlib/basemap#534]
while running a program using basemap ..the following error is seen

Warning: Basemap package cannot be imported | No module named 'pyproj._list'  error detected - Groundtrack plot disabled!
Traceback (most recent call last):
  File "C:\Users\hp\Python\gnsspynos.py", line 20, in <module>
    from mpl_toolkits.basemap import basemap
  File "E:\Program Files\Python\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 46, in <module>
    import pyproj
  File "E:\Program Files\Python\lib\site-packages\pyproj\__init__.py", line 52, in <module>
    from pyproj._list import (  # noqa: F401
ModuleNotFoundError: No module named 'pyproj._list'

please help with the issue

**Comment by molinav** [comment]
This looks like a problem in `pyproj` and not in `basemap`. The main `basemap` init file only references public members of `pyproj`. Your error says that `pyproj` itself fails to import because it tries to access a private module that cannot be found.

Can you provide info about your environment? Python version, `basemap` version, `pyproj` version. If you are working with Python 3.10 (as I remember from one of your previous issues), I have just tested it with `basemap` 1.3.2 and `pyproj` 3.3.0 and the `basemap` import works normally.

**Comment by molinav** [comment]
I am closing this issue due to lack of feedback. It seems to be a problem from the `pyproj` installation and not from `basemap` itself, and without feedback there is not much to do here.
