### ISSUE TITLE
install basemap in  Google colab

### ISSUE THREAD

**Issue by SalvatoreRa** [matplotlib/basemap#535]
Hi, 

I have tried to install basemap in colab, I tested some alternatives but none of them worked.

I tried also the proposed solution find in StackOverflow, without success

https://stackoverflow.com/questions/54613992/how-to-install-and-use-basemap-on-google-colab

How I can install basemap in Colab?

best

**Comment by molinav** [comment]
Hi @SalvatoreRa!

Can you try to install it with the solution that I posted here?
https://stackoverflow.com/a/70624545/13312069

Since version 1.3.0 we have precompiled wheels in PyPI, so you can install `basemap` in Google Colab as any other package:
```sh
!pip install basemap
```

In case you need the high-resolution datasets, you need to install them manually:
```sh
!pip install basemap-data-hires
```

**Comment by SalvatoreRa** [comment]
> Hi @SalvatoreRa!
> 
> Can you try to install it with the solution that I posted here? https://stackoverflow.com/a/70624545/13312069
> 
> Since version 1.3.0 we have precompiled wheels in PyPI, so you can install `basemap` in Google Colab as any other package:
> 
> ```shell
> !pip install basemap
> ```
> 
> In case you need the high-resolution datasets, you need to install them manually:
> 
> ```shell
> !pip install basemap-data-hires
> ```

thanks, It worked well

**Comment by molinav** [comment]
Perfect! Then I think we can close this issue.
