### ISSUE TITLE
epoto failed to show with pseudocyl projection

### ISSUE THREAD

**Issue by YilongWang** [matplotlib/basemap#577]
I have the basemap-1.3.7 and matplotlib-3.7.1. 
When the projection is "moll" or "robin", epoto will show nothing. 
It can be fixed to add "fill_color='none'" on Line 3206 of \_\_init\_\_.py
In addition, with these projections, the left and right sides of the map have the same longitude, so the x and y in meters will be confused when lon_0 is larger than 0.
I tried to fix this problem with the following steps, though very roughly:
(1) In \_\_init\_\_.py, on Line 4184, subtract 1e-10 from lonright; on L4185 add 1e-10 to lonleft:
     lonright = lon_0+180.-1e-10
     lonleft = lon_0-180.+1e-10
(2) In proj.py, on Line 199 and Line 240, subtract -1e-10 from urcrnrx: 
     urcrnrx,xtmp = self(projparams['lon_0']+180.-1e-10,0)

**Comment by molinav** [comment]
Hi @YilongWang! Thanks for reporting this issue. I am currently a bit busy, but I will come back to this issue as soon as I can find a spot in my calendar.

**Comment by molinav** [comment]
Sorry for being so delayed with this, @YilongWang! I have just pushed the commit with your correction related to the images being shown behind the map background.

I keep this issue open while I correct your other proposal, since it gives the hints for #463. Once I correct this, both issues will be closed. Thank you for your contributions!

**Comment by molinav** [comment]
I am closing here, since the image showing issue should be fixed now. Thanks again, @YilongWang!
