### ISSUE TITLE
Segmentation Fault due To build conflicts

### ISSUE THREAD

**Issue by SoundsSerious** [matplotlib/basemap#588]
Hi, I'm observing a segmentation fault as described in https://github.com/jupyter/qtconsole/issues/585 of which I believe basemap is the root cause.

This is due to underlying conda c-library conflicts. 

It seems the underlying issue with basemap support is the build process for `libgeos`. I wonder if life would be easier by making calls to https://pygeos.readthedocs.io/en/stable/ instead?

**Comment by SoundsSerious** [comment]
To replicate this issue, this is the minimal build script that results in failure.

```
conda env remove nept -y
conda create -n nept -c conda-forge  python=3.9.12 -y
conda activate nept
conda install -c conda-forge basemap qtconsole -y
jupyter qtconsole #This fails with segmentation fault.
```

**Comment by DWesl** [comment]
If the issue at hand is C library conflicts, that requires two packages both requiring the same C library, but vendoring/shipping different versions of it.  I can see raising the issue here to get help re-compiling basemap with whatever version of geos the other library uses, but that doesn't seem to be what you're after.

Since the problem as stated is that conda is installing an invalid environment, might I ask why you did not move the issue to the conda repo?  There is a decent chance conda is doing the best it can with the information it has, in which case, have you tried raising this issue with the conda-forge maintainers and asking them to use the same version of geos for building basemap and the other package?

[Here's where conda-forge declares basemap needs geos to build](https://github.com/conda-forge/basemap-feedstock/blob/5ea984898a3a7012ff48d9cef1ae9022f345a9f7/recipe/meta.yaml#L54), though it looks like it specifies that the geos version installed at runtime must match that used at build time, so conflicts would be on the other package pulling in geos (presumably without that specification). It sounds like you think qtconsole is the other package that depends on geos, [but it looks like the only C library qtconsole directly depends on is python](https://github.com/conda-forge/qtconsole-feedstock/blob/cbe00e6a15ab4ec5d198af78476c0db107b811f8/recipe/meta.yaml#L20).  Of the other packages installed in the log on the previous post, the only ones that look likely to link against geos are dependencies of basemap (build dependencies, even).

If you're just looking for workarounds, have you checked the versions of the installed packages on the working version, then attempted to install exactly those versions (except for the different python, since you want that to be 3.9)?  There is an excellent chance this won't work, but using `<${version}` instead of `==${version}` might.  What about the other way around?  Does installing the package versions used by the broken installation with the newer python fix things?

I'm not seeing any obvious reason you can consistently crash qtconsole while everyone helping you can run qtconsole just fine, so could you try installing just basemap (no qtconsole) and seeing if that produces decent plots in the normal python console, then just qtconsole (without basemap) to try your test, then qtconsole and matplotlib (still no basemap), and seeing which versions cause problems?

What does `pip list --user` show? Is there anything there that would have a different version of geos than that used for the py39 build of basemap?

I'm suspecting you haven't set `LD_PRELOAD`, but `echo "${LD_PRELOAD}"` could check that.  Does it mention a `libgeos.so*`?  What of your `LD_LIBRARY_PATH`, is there a directory with a `libgeos.so*` before the conda environment's lib directory (`echo "${LD_LIBRARY_PATH} | tr ':' '\n'`)?

Perhaps I am missing something.  Could you explain why you think "the underlying issue with basemap support is the build process for libgeos"?  I do remember `libgeos` conflicts causing problems, when two packages that link against geos bundled it as part of their wheels, but you're using conda, not pip, and the tools to avoid that problem have gotten better in the last decade.

Do other jupyter front-ends (`jupyter console` and `jupyter notebook`) cause the same problem?  What about using the QtAgg or QtCairo backends for matplotlib when creating a figure using basemap?

Out of curiousity, what version of conda are you using?  `conda env remove nept -y` doesn't work for me (with conda 23.11) unless I add `-n` before `nept`.  What happens if you try running `conda clean -a` between deleting the old environment and creating the new one?

**Comment by SoundsSerious** [comment]
Hi I was able to solve this issue by reinstalling conda and cleaning its installation first. Sorry for not replying sooner.

I recall made a number of mistakes mixing repos from pip and the conda forge install which I think made it harder to debug.
