### ISSUE TITLE
FAQ refers to file that was replaced

### ISSUE THREAD

**Issue by timcoote** [matplotlib/basemap#592]
FAQ refers to the file `ireland.py` as an example of how to caches country shapes (to paraphrase the statement). This file was replaced by `hires.py` some while ago.

**Comment by molinav** [comment]
Hi, @timcoote! Thanks for reporting the issue. You are totally right. In addition, I checked the `hires.py` and it is a bit misleading, because the pickled `Basemap` instance is loaded as `m2` but the next lines of code use `m`, which is the original `Basemap` instance, and it should be `m2` instead. I will correct all this now.

**Comment by molinav** [comment]
The corrections are pushed to the hotfix branch for `basemap` 1.3.9. Thanks again!
